global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus-cordada'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['cordada-cms-rwyb.onrender.com']
  - job_name: 'prometheus-drizzle'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['drizzle-app-1:8081']
